# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.ImageField(upload_to='images/%Y/%m/%d')),
                ('caption', models.TextField()),
                ('url', models.CharField(blank=True, max_length=128, verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('opened', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=128)),
                ('hypothesis', models.TextField(blank=True)),
                ('discussion', models.TextField(blank=True)),
                ('shelved', models.BooleanField(default=False)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('related', models.ManyToManyField(blank=True, to='logger.Investigation')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('summary', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Investigation')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='image',
            name='log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logger.Log'),
        ),
    ]
