# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='log',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='log',
            old_name='date',
            new_name='created',
        ),
    ]
