# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20160415_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='logger.Log'),
        ),
    ]
