# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 17:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0002_auto_20160414_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='last_edit',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 14, 17, 5, 24, 600973)),
            preserve_default=False,
        ),
    ]
