# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_log_last_edit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investigation',
            name='discussion',
        ),
    ]
