# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0003_auto_20160415_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='log',
        ),
        migrations.AddField(
            model_name='image',
            name='log',
            field=models.ManyToManyField(blank=True, to='logger.Log'),
        ),
    ]
